var pokemonCharacters = { profiles: [
  {
    name: "Bulbasaur",
    image_url: "img/bulbasaur.png",
    category: "Seed",
    abilities: "Overgrow",
    type: ["grass", "poison"],
    weaknesses: ["fire", "flying", "ice", "psychic"]
  },
  {
    name: "Charmeleon",
    image_url: "img/charmeleon.png",
    category: "Flame",
    abilities: "Blaze",
    type: ["fire"],
    weaknesses: ["ground", "rock", "water"],
  },
  {
    name: "Blastoise",
    image_url: "img/blastoise.png",
    category: "Shellfish",
    abilities: "Torrent",
    type: ["Water"],
    weaknesses: ["Electric", "Grass"],
  },
  {
    name: "Butterfree",
    image_url: "img/butterfree.png",
    category: "Butterfly",
    abilities: "Compound Eyes",
    type: ["bug", "flying"],
    weaknesses: ["rock", "electric", "fire", "flying", "ice"],
  },
  {
    name: "Beedrill",
    image_url: "img/beedrill.png",
    category: "Poison Bee",
    abilities: "Swarm",
    type: ["bug", "poison"],
    weaknesses: ["fire", "flying", "psychic", "rock"],
  },
  {
    name: "Pidgey",
    image_url: "img/pidgey.png",
    category: "Tiny Bird",
    abilities: "Keen Eye",
    type: ["normal", "flying"],
    weaknesses: ["electric", "ice", "rock"],
  },
  {
    name: "Raticate",
    image_url: "img/raticate.png",
    category: "Mouse",
    abilities: "Run Away",
    type: ["normal"],
    weaknesses: ["fighting"],
  },
  {
    name: "Arbok",
    image_url: "img/arbok.png",
    category: "Cobra",
    abilities: "Shed Skin",
    type: ["poison"],
    weaknesses: ["ground", "psychic"],
  },
  {
    name: "Pikachu",
    image_url: "img/pikachu.png",
    category: "Mouse",
    abilities: "Static",
    type: ["electric"],
    weaknesses: ["ground"],
  },
  {
    name: "Sandslash",
    image_url: "img/sandslash.png",
    category: "Mouse",
    abilities: "Sand Veil",
    type: ["ground"],
    weaknesses: ["grass", "ice", "water"],
  },
  {
    name: "Nidorino",
    image_url: "img/nidorino.png",
    category: "Poinson Pin",
    abilities: "Poinson Point",
    type: ["Poison"],
    weaknesses: ["ground", "psychic"],
  },
  {
    name: "Jigglypuff",
    image_url: "img/jigglypuff.png",
    category: "Balloon",
    abilities: "Cute Charm",
    type: ["normal", "fairy"],
    weaknesses: ["steel", "poison"],
  },
  {
    name: "Paras",
    image_url: "img/paras.png",
    category: "Mushroom",
    abilities: "Effect Spore",
    type: ["bug", "grass"],
    weaknesses: ["fire", "flying", "bug", "ice", "poison", "rock"],
  },
  ]}